name: flutter_code_image
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Google font
  google_fonts: 6.1.0

  # State Management
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # Screenshot
  screenshot: ^2.1.0

  # Rich text controller
  rich_text_controller: ^1.4.2

  # Lottie Animation
  lottie: ^3.1.0

  # Auto Size text
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  mobx_codegen: ^2.6.0+1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
   - assets/
